const asList = (items = []) => {
  if (!Array.isArray(items) || !items.length) return 'Not available';
  return items.map((item) => `- ${item}`).join('\n');
};

const asObjectList = (items = [], formatter) => {
  if (!Array.isArray(items) || !items.length) return 'Not available';
  return items.map(formatter).join('\n');
};

const buildTextReport = (analysisResult) => {
  const repository = analysisResult.repository || {};
  const analysis = analysisResult.analysis || {};

  return [
    'RepoLens Repository Analysis Report',
    '===================================',
    '',
    `Repository: ${repository.fullName || repository.name || 'Unknown'}`,
    `URL: ${repository.url || analysisResult.repositoryUrl || 'Not available'}`,
    `Description: ${repository.description || 'Not available'}`,
    `Default Branch: ${repository.defaultBranch || 'Not available'}`,
    `Primary Language: ${repository.language || 'Not available'}`,
    `Stars: ${repository.stars ?? 'Not available'}`,
    `Forks: ${repository.forks ?? 'Not available'}`,
    `Open Issues: ${repository.openIssues ?? 'Not available'}`,
    `License: ${repository.license || 'Not available'}`,
    '',
    'Project Summary',
    '---------------',
    analysis.projectSummary || 'Not available',
    '',
    'Project Purpose',
    '---------------',
    analysis.projectPurpose || 'Not available',
    '',
    'Project Type',
    '------------',
    analysis.projectType || 'Not available',
    '',
    'Tech Stack',
    '----------',
    asList(analysis.techStack?.length ? analysis.techStack : analysisResult.techStack),
    '',
    'Features',
    '--------',
    asList(analysis.features),
    '',
    'Architecture Overview',
    '---------------------',
    Array.isArray(analysis.architectureOverview)
      ? asList(analysis.architectureOverview)
      : analysis.architectureOverview || 'Not available',
    '',
    'Setup Instructions',
    '------------------',
    asList(analysis.setupInstructions),
    '',
    'Folder Explanation',
    '------------------',
    asObjectList(
      analysis.folderExplanation,
      (folder) => `- ${folder.path}: ${folder.explanation}`,
    ),
    '',
    'Important File Explanations',
    '---------------------------',
    asObjectList(
      analysis.importantFiles,
      (file) => `- ${file.path}: ${file.explanation}`,
    ),
    '',
    'Beginner-Friendly Explanation',
    '-----------------------------',
    analysis.beginnerExplanation || 'Not available',
    '',
    'Recruiter-Friendly Explanation',
    '------------------------------',
    analysis.recruiterExplanation || 'Not available',
    '',
    'Suggestions',
    '-----------',
    asList(analysis.suggestions),
    '',
    'Security Suggestions',
    '--------------------',
    asList(analysis.securitySuggestions),
    '',
    'Dependency Insights',
    '-------------------',
    asList(analysis.dependencyInsights),
    '',
    'Code Quality Score',
    '------------------',
    `${analysis.codeQualityScore?.score ?? 'Not available'} / 100`,
    analysis.codeQualityScore?.rationale || '',
    '',
    'Important Files',
    '---------------',
    asObjectList(
      analysisResult.importantFiles,
      (file) => `- ${file.path} (${file.size || 0} bytes)`,
    ),
    '',
    'Generated by RepoLens',
  ].join('\n');
};

export const exportReport = (analysisResult) => {
  if (!analysisResult) return;

  const fileName = `${analysisResult.repository?.name || 'repository'}-repolens-report.txt`
    .replace(/[<>:"/\\|?*]+/g, '-')
    .toLowerCase();
  const blob = new Blob([buildTextReport(analysisResult)], {
    type: 'text/plain;charset=utf-8',
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 100);
};
